### PR TITLE
Performance improvement for Doudizhu's utils.contains_cards() and game._get_others_current_hand()

### PR DESCRIPTION
**Pull request by billmuch**
Should use merge sort instead of add two lists and sort again when merge two sorted lists together.

The performance improved more than 35 times.

### CODE REVIEW

**Comment by billmuch** [comment]
Seems runs 350% faster or more than before :)

**Comment by daochenzha** [comment]
@billmuch Thank you! Actually, in our preliminary tests, we found that initializing the Judger class took a lot of time.
https://github.com/datamllab/rlcard/blob/master/rlcard/games/doudizhu/judger.py#L14
It seems that optimizing the performance contains_cards is right direction to accelerate the initialization :)

Thank you. We will review the codes shortly.

**Comment by daochenzha** [comment]
@billmuch Thank you! Actually, in our preliminary tests, we found that initializing the Judger class took a lot of time.
https://github.com/datamllab/rlcard/blob/master/rlcard/games/doudizhu/judger.py#L14
It seems that optimizing the performance contains_cards is right direction to accelerate the initialization :)

Thank you. We will review the codes shortly.

**Comment by billmuch** [comment]
@daochenzha I targeted for those time consume functions used when play instead of used when initialize a game. Since initialize a game only did once for a whole game and should not be the problem for my train now. 
So the improvement of judger.__init__ is just a side effect. :)
For the judger.__init__, one thing we can try is rules base "playable cards generator from player's current_hand". It seems generate from current_hand may be more faster than test all 33675 playable cards again player's current_hand.

From my point of view, the root cause of the performance issue of the Doudizhu is that the character based cards representation we are using now is friendly to human but not friendly to computation. Especially the "order" for the cards (3456789TJQKA2) is not even ordered for computer. 
So a better implementation may use ordered integer arrays or numpy's datatype to represent cards/hands internally for computation. And convert it to human friendly strings whenever needed.

**Comment by daochenzha** [comment]
@billmuch I totally agree. For search based algorithms such as CFR, initialization may not be a problem. However, for sampling based method such as NFSP, lots of games will be played, and thus the initialization will be called lots of times.

Thank you for the suggestion of using integer card representation. It seems to be a promising direction to improve the performance. However, my main concern about using integer representation is that we may not be able to flexibly adjust the state representation. Currently, we can easily adjust state representation in the Env wrapper. However, if using integer internally, it may need to first translate integers to characters and then we can encode the state. Do you happen to have some comments on this? Thanks :)

**Comment by billmuch** [comment]
@daochenzha The numpy matrix you are suggesting in the models can also be a good option for cards representation internally. If we can figure out a efficient way to do the "contain_cards" test. 

Since changing the data structure of the cards inside Doudizhu needs a lot of efforts to do, I think we can keep on optimizing the current one until the performance of the engine is proven to be the problem for some algorithm, then the new data structure can be tried. 

I will try the rule base playable card generator for judger.__init__ to see whether the performance can improved. 

After that, the big problem for me should be the memory compression since there are too many states for the Doudizhu when using CFR. 
It's appreciated if you have any ideas can shared with me. :)

**Comment by daochenzha** [comment]
@billmuch Thanks for the comments! I would say, maybe we we can first do some small tests on the internal numpy representation. For example, we can test it on contain_cards. If it seems to work, then we can consider refractor the data structure.

I think whether numpy can accelerate the contain_cards will depend on how we implement the function,and also the internal representations. If we can implement it nicely, we may have a better performance since numpy internally optimize the speed with multi-threading.

**Pull request merged**
