### PR TITLE
Corrections for Gin Rummy.

### PR DESCRIPTION
**Pull request by billh0420**
You need to change the web page http://rlcard.org/games.html to match the changes to docs/games.md about the following two items:

1) The losing player is punished by the negative of their deadwood count divided by 100.

2) If the hand is declared dead, both players are punished by the negative of their deadwood count divided by 100.

### CODE REVIEW

**Comment by daochenzha** [comment]
@billh0420 I observe that the gin-rummy GUI code has very low testing coverage and codacy posts lots of complaints on the code, see https://app.codacy.com/manual/daochenzha/rlcard/dashboard.

We will be grateful if you could kindly provide some testing scripts and improve the code based on the posted issues.

**Comment by billh0420** [comment]
About codacy "Unused List imported from typing" message:

I am using PyCharm to do my Python coding. Python 3.5 allows type checking of variables to be put into comments. If I delete the "from typing import List" line, then PyCharm gives me a warning about "unresolved reference 'List'".

I would like to keep the ability to type check. Otherwise, I will have to delete the typing comments if you want me to delete and not use the 'typing' module. Is this what you want me to do: not use the typing module?

**Comment by daochenzha** [comment]
@billh0420 I think the typing could be kept if it is useful. Just dealing the issues that make sense will be good enough.

**Comment by billh0420** [comment]
About codacy "Use of assert detected. The enclosed code will be removed when compiling to optimised byte code." message:

I like to use assert when coding. The assert should not be raised when the code is released. If it is raised, then I think the program should fail even if it is in production. If the code is compiled to optimized byte code, then the assert will be removed anyway.

Question: Do you want me to remove my assert statements or just treat the codacy message as something to note?

**Comment by daochenzha** [comment]
@billh0420 I think assert is not a common practice for code in package. This can be changed to raise errors. BTW, could you kindly pull dev branch before making any change? Some new features are added. There could be many conflicts between dev and master

**Comment by billh0420** [comment]
I can change assert to raise error. Is it ok to not catch such errors and let the program terminate?

I have been pulling dev into my forked dev. Do I have to worry about master?

**Comment by daochenzha** [comment]
@billh0420 It would be ok. I think the point of raising error is that it is more informative than assert. It allows printing texts and values. These are more helpful than assert for users to debug.

No need to care about master. Dev will be merged to master once it is stable.

**Pull request merged**
