### PR TITLE
Rule based playable cards generator to speed up game initialization.

### PR DESCRIPTION
**Pull request by billmuch**
Use rule based playable cards generator instead of use  contains_cards to test against all playable cards of a deck.

Init a game can be speed up by 28.5%.

### CODE REVIEW

**Comment by billmuch** [comment]
If the change is acceptable, a Playable Cards Generator class can be made for player's to get playable cards according to TYPE. This can also speed up the speed of the game engine.

**Comment by daochenzha** [comment]
@billmuch Hello! Thank you for your efforts! We need some time to check the logic of the Playable Cards Generator. BTW, may I know why you close this request?

**Comment by billmuch** [comment]
@daochenzha Thank you for your review. I close this pull request because it broken the unittest. For the rule has been changed during I write this module. (https://github.com/datamllab/rlcard/pull/46)
I was trying to fix it, but need to confirm with you guys the rule first. 
I have send a mail to daochen.zha at tamu.edu and yuanpucao at gmail.com about this, but it seems 
the mail was considered as junk mail. Are these email addresses correct?

**Comment by daochenzha** [comment]
@billmuch My email address is correct. But I did not receive it. It is weird. We are still reviewing the logic (pretty busy recently). For the rules, @CaoYuanpu has studied it carefully. He should be able to give the correct rule. Thank you again for your efforts :)

**Comment by billmuch** [comment]
@daochenzha Could you send a mail to 7769521 at qq.com? It will be convenient for me to contact you guys. By the way, my wechat id is 13062815146. 
And please review following cases that are legal ( in CARD_TYPE[1]) for current rule.
Case 1: 222 is legal for trio_chain and 22 or 2 is not legal for solo_chain and pair_chains. 
Case 2: according to the [image](https://user-images.githubusercontent.com/42167703/70057008-643d0180-1617-11ea-94dd-f262bbadd781.png) BR can not be the attachment for fours. 

LEGAL pattern in CARD_TYPE[1]:
        QQQKKKAAA222
	JJJQQQKKKAAA222B
	JJJQQQKKKAAA222R
	3JJJQQQKKKAAA222
	4JJJQQQKKKAAA222
	5JJJQQQKKKAAA222
	6JJJQQQKKKAAA222
	7JJJQQQKKKAAA222
	8JJJQQQKKKAAA222
	9JJJQQQKKKAAA222
	TJJJQQQKKKAAA222
	3TTTJJJQQQKKKAAA222B
	4TTTJJJQQQKKKAAA222B
	5TTTJJJQQQKKKAAA222B
	6TTTJJJQQQKKKAAA222B
	7TTTJJJQQQKKKAAA222B
	8TTTJJJQQQKKKAAA222B
	9TTTJJJQQQKKKAAA222B
	3TTTJJJQQQKKKAAA222R
	4TTTJJJQQQKKKAAA222R
	5TTTJJJQQQKKKAAA222R
	6TTTJJJQQQKKKAAA222R
	7TTTJJJQQQKKKAAA222R
	8TTTJJJQQQKKKAAA222R
	9TTTJJJQQQKKKAAA222R
	33TTTJJJQQQKKKAAA222
	34TTTJJJQQQKKKAAA222
	35TTTJJJQQQKKKAAA222
	36TTTJJJQQQKKKAAA222
	37TTTJJJQQQKKKAAA222
	38TTTJJJQQQKKKAAA222
	39TTTJJJQQQKKKAAA222
	44TTTJJJQQQKKKAAA222
	45TTTJJJQQQKKKAAA222
	46TTTJJJQQQKKKAAA222
	47TTTJJJQQQKKKAAA222
	48TTTJJJQQQKKKAAA222
	49TTTJJJQQQKKKAAA222
	55TTTJJJQQQKKKAAA222
	56TTTJJJQQQKKKAAA222
	57TTTJJJQQQKKKAAA222
	58TTTJJJQQQKKKAAA222
	59TTTJJJQQQKKKAAA222
	66TTTJJJQQQKKKAAA222
	67TTTJJJQQQKKKAAA222
	68TTTJJJQQQKKKAAA222
	69TTTJJJQQQKKKAAA222
	77TTTJJJQQQKKKAAA222
	78TTTJJJQQQKKKAAA222
	79TTTJJJQQQKKKAAA222
	88TTTJJJQQQKKKAAA222
	89TTTJJJQQQKKKAAA222
	99TTTJJJQQQKKKAAA222
	3333BR
	4444BR
	5555BR
	6666BR
	7777BR
	8888BR
	9999BR
	TTTTBR
	JJJJBR
	QQQQBR
	KKKKBR
	AAAABR
	2222BR

**Pull request closed without merging**
