### PR TITLE
Less actions and some bugs

### PR DESCRIPTION
**Pull request by AdrianP-**
I've reduced the action space for the NL Holdem (WIP, more actions to add in the near future) and I've seen some bugs related to the stake and bets management. 

For instance, I didn't see the necessity of current_raise_amount variable. Also when you raise all, the env didn't work well.

Also, I propose a new way to handle the actions

### CODE REVIEW

**Comment by ruzhwei** [comment]
Thanks for your contribution! However, we are confused about why you reduce the action space and propose a new way to handle actions. Besides, could you please provide a thorough explanation of your reason to add pot and stages?

**Comment by daochenzha** [comment]
@AdrianP We have a discussion about your proposed implementation. We think the changes are nice. Just one question on the action space. It seems that in your implementation, you have decreased the action space. In our original implementation, we use a larger action space from 1-100. Of course, decreasing the action space will make the environment easier. I am not sure which one is better. So could you justify your choice of action spaces? Thanks.

**Comment by AdrianP-** [comment]
Hi, that is, the goal of reducing the action space is to reduce the exploring time and the tree of actions. It also has more sense with the real play of Poker. 
When you are playing, there is no real difference between 50 or 53 "chips". Usually, the bets are x Times the big blind or bets related with the Pot.

Moreover, the Pot and Stage data is for feed the state info due to the behavior of the players are dynamical (the strategy on the Flop is not the same as the River etc)

**Comment by AdrianP-** [comment]
I just add new features: 
- Control the pot through dealer
- When everyone is in allin state, the game continue by itself until the finish.
- In some cases, you can bet more than your stake. Fix it

**Pull request merged**
