### PR TITLE
number of players argument

### PR DESCRIPTION
**Pull request by kaanozdogru**

### CODE REVIEW

**Comment by justinkterry** [comment]
@daochenzha this is on the correct branch. Once this is merged can you please cut a release of rlcard? we want to add a number of players argument to the pettingzoo environments

**Comment by daochenzha** [comment]
@justinkterry Thanks for reminding me. We use a different way to add configs, see https://github.com/datamllab/rlcard/blob/master/rlcard/games/blackjack/game.py#L16 I will add the player name as a config. A new version will be released soon.

**Comment by daochenzha** [comment]
@justinkterry @kaanozdogru In the master branch, I have supported multi-players for Leduc and UNO. However, DouDizhu and Mahjong usually have fixed number of players of 3 and 4, respectively, according to their rules. Thus, I haven't supported multi-players for now since changing the number of players may cause some logical errors. The new version will be released soon after we clean the code. Thanks!

**Comment by justinkterry** [comment]
@kaanozdogru you can close this one

**Pull request closed without merging**
