### PR TITLE
Multi agent blackjack implemented

### PR DESCRIPTION
**Pull request by Clarit7**
I change codes for multi agent play of blackjack.
But I have to change state dictionary to get all agents' hands information, and dict state now have more than 4 keys (action, state, player0 hand, player1 hand, ... , dealer hand)
Although key 'state' have duplicated information with key 'player hand' and 'dealer hand', I couldn't remove it because it will affects to other codes. (Like dqn agent)
So multi agent play is only available for human and random agent

### CODE REVIEW

**Comment by daochenzha** [comment]
@Clarit7 Hi, thanks for contributing. I have checked code and planned to merge the PR. However, I find there are many conflicts in this PR. This may because your cloned version is out of date. Because we add some functionalities like local random seeds, the conflicts are hard to resolve. Could you reclone the repo and send another PR? Thanks!

**Comment by Clarit7** [comment]
Thanks for replying :)

I'll rewrite them with latest version today!

2020년 6월 2일 (화) 오후 1:07, Daochen Zha <notifications@github.com>님이 작성:

**Comment by Clarit7** [comment]
Conflict problems are solved. I just made conflicted parts from codes to annotations. So after merge, you can remove them.

**Comment by daochenzha** [comment]
Great! Thanks!

**Comment by daochenzha** [comment]
@Clarit7 Hi, I double check the code. I feel like I need to revert the commits, because it seems that your commits will make the dqn training broken and testing failed. Could you double-check your commits? I found some outstanding issues:

1. The payoffs return a list; however, the current version requires that the payoff is a numpy array because we add multi-processing running, which will return a list. This will cause some issues in `tounament` function (it is a problem caused by out-of-date, so I still recommend you re-fork the repo and modify)
2. For the state change, I don't think it is necessary. This change will make the state weird, since a player should not have access to others' information. There is an interface called `get_perfect_informtion`, which I think it should be more suitable for this purpose.
3. For the number of players, I would recommend adding a new key in `config` to specify the player number with a default value of `1`. In this way, we the examples of DQN would still work.
4. For some changes, it would also need changing the testing files to avoid building fails.

Please let me know if you have any other thoughts. Thank!

**Comment by Clarit7** [comment]
Ok, sorry for these issues. I'll try again after you revert codes.
But I have a question about get_perfect_information.
env calls human agent like this

        while not self.is_over():
            # Agent plays
            if not is_training:
                action, _ = self.agents[player_id].eval_step(state)

As I know, in blackjack all people can see other's hands too. So I wanted to give all people's hand information to human agent, but in state, only self hand information exist. It made me change state structure.
Without change structure, how can It print other's hands information in human agent?

**Comment by daochenzha** [comment]
@Clarit7 Thanks for the reply! Yes you are right. I misunderstood the rules. Your modification on the state makes sense to me.

**Comment by Clarit7** [comment]
That's alright. But I wonder if I change state, will it cause problems to dqn agent? Because I didn't care about that while I write a code.

**Comment by daochenzha** [comment]
It is possible but can be fixed. Dqn uses numerical representation for learning. This part is defined in _extract_state in https://github.com/datamllab/rlcard/blob/master/rlcard/envs/blackjack.py#L31

This function essentially transforms some of the text to numerical value. If changing state unfortunately affect dqn, the problem can be always fixed by modifying this function.

**Comment by Clarit7** [comment]
Thanks! So your requirement are like these :
1. Payoffs should return np.array(list)
2. It is ok to change state structure
3. Adding a new key 'num_player' to config in env (defalut = 1)
4. Test other example files

Am i understanding correctly?

**Comment by daochenzha** [comment]
Yes. Thanks for the summary.

**Pull request merged**
