### PR TITLE
Train agents using PettingZoo environments

### PR DESCRIPTION
**Pull request by ycheng517**
Provide examples of training agents on PettingZoo environments using the AEC games model. Agents are wrapped so that they are compatible with the PettingZoo API. Note that the CFR agent isn't able to get included since PettingZoo does not support step back.

I've verified that the agents obtain comparable performance on the PettingZoo environments as the original RLCard environments.

### CODE REVIEW

**Comment by daochenzha** [comment]
@ycheng517 Thanks for the contribution! It looks pretty good. Just one question. I saw that you added an optional dependency of pettingzoo in setup.py. I am just curious whether it will work since pettingzoo also has an optional dependency on rlcard.

**Comment by benblack769** [comment]
@daochenzha Yes, this optional dependency in RLCard should not be a problem because it only installs the base pettingzoo package, not the optional "classic" dependency which installs RLCard. So there is no cycle

**Comment by ycheng517** [comment]
@daochenzha thanks for the feedback. I'm working on adding the rest of the agents. Regarding the pettingzoo dependency in `setup.py`, turns out `pettingzoo[classic]` is needed, so there would be the cyclic dependency. Maybe in a README file for running the agents using Pettingzoo environments, I can mention that one should simply install `pettingzoo[classic]` and run the training scripts. (cc @benblack769 )

**Comment by benblack769** [comment]
@ycheng517 What specific dependencies within pettingzoo[classic] do you need? I would try to install those instead, rather than the aggregate pettingzoo[classic].

**Comment by daochenzha** [comment]
@ycheng517 @ycheng517 @benblack769 It looks great! Thanks for the contribution @ycheng517

Just merged to the master branch. I have also added some links in the README to point the users to the PettingZoo examples.

**Pull request merged**
